EmployeeDirectory/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EmployeeDirectory.Controllers
{
    public class LoginController : Controller
    {

        //public ActionResult Login(string Email, string Password)
        //{
        //    EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
        //    string newConnection = connectionString.connectionString;


        //    // getting email and password from Stafflogin
        //    string SELECT = $"SELECT '{Email}' AND '{Password}' FROM StaffLogin";

        //    Console.WriteLine("Connecting to SQL Server.");

        //    // establishing a connection to our database
        //    SqlConnection connection = new SqlConnection(newConnection);
        //    using (connection)
        //    {
        //        // taking the command 'SELECT' from database and applying it here 
        //        SqlCommand cmd = new SqlCommand(SELECT, connection);
        //        // opening the connection to allow data to pass
        //        connection.Open();

        //    }


        //    return RedirectToAction("Select");
        //}
    }
}

EmployeeDirectory/Controllers/MethodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EmployeeDirectory.Controllers
{
 

    public class MethodsController : Controller
    {

        public IActionResult Insert()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }


        public ActionResult Login(string Email, string Password)
        {
            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;


            // getting email and password from Stafflogin
            string SELECT = $"SELECT * FROM StaffLogin WHERE Email = '{Email}' AND Password = '{Password}' ";

            Console.WriteLine("Connecting to SQL Server.");

            // establishing a connection to our database
            SqlConnection connection = new SqlConnection(newConnection);
            using (connection)
            {
 
                SqlCommand cmd = new SqlCommand(SELECT, connection);
                connection.Open();

                using (SqlDataReader reader = cmd.ExecuteReader())
                {

                    while (reader.Read())
                    {

                        var employeeLogin = new EmployeeDirectory.Models.EmployeeLogin();

                        employeeLogin.Email = reader["Email"].ToString();
                        employeeLogin.Password = reader["Password"].ToString();


                        if (employeeLogin == null)
                        {
                            ViewBag.error = "Error";
                            return View();

                        }
                        else
                        {
                            return RedirectToAction("Select");
                        }
                    }
                    return View();

                }
            }
        }


            
        





        public ActionResult Select()
        {
            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;
            

            // getting all data from StaffModel
            string SELECT = "SELECT * FROM StaffModel";

            Console.WriteLine("Connecting to SQL Server.");

            // establishing a connection to our database
            SqlConnection connection = new SqlConnection(newConnection);
            using (connection)
            {
                // taking the command 'SELECT' from database and applying it here 
                SqlCommand cmd = new SqlCommand(SELECT, connection);
                // opening the connection to allow data to pass
                connection.Open();

                // creating a new variable, 'model', turning it into a list.
                var model = new List<EmployeeDirectory.Models.EmployeeModel>();

                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {

                        var employeeDetails = new EmployeeDirectory.Models.EmployeeModel();
                        // where is this coming from? Models Folder/EmployeeModel Class
                        // creating a new variable, 'employeeDetails', that passes values for the list.
                        employeeDetails.EmployeeID = (int)reader["EmployeeID"];
                        employeeDetails.EmployeeName = reader["EmployeeName"].ToString();
                        employeeDetails.JobTitle = reader["JobTitle"].ToString();
                        employeeDetails.WorkPlace = reader["WorkPlace"].ToString();
                        employeeDetails.Email = reader["Email"].ToString();
                        employeeDetails.PhoneNumber = reader["PhoneNumber"].ToString();

                        // model = list and adds employeeDetails to a list format
                        model.Add(employeeDetails);

                    }
                }
                connection.Close();
                // returns the model (which now has data)
                return View(model);
            }
        }

        public ActionResult Search(int EmployeeID)
        {
           
            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;
            var employeeDetails = new EmployeeDirectory.Models.EmployeeModel();
            string SEARCH = $"SELECT * FROM StaffModel WHERE EmployeeID={EmployeeID}";

            SqlConnection connection = new SqlConnection(newConnection);
            using (connection)
            {
                SqlCommand cmd = new SqlCommand(SEARCH, connection);
                connection.Open();
                var model = new List<EmployeeDirectory.Models.EmployeeModel>();
                using (SqlDataReader reader = cmd.ExecuteReader())
                {

                        while (reader.Read())
                        {
                            
                            employeeDetails.EmployeeID += (int)reader["EmployeeID"];
                            employeeDetails.EmployeeName += reader["EmployeeName"].ToString();
                            employeeDetails.JobTitle += reader["JobTitle"].ToString();
                            employeeDetails.WorkPlace += reader["WorkPlace"].ToString();
                            employeeDetails.Email += reader["Email"].ToString();
                            employeeDetails.PhoneNumber += reader["PhoneNumber"].ToString();
                            //Console.WriteLine(employeeDetails);
                            model.Add(employeeDetails);

                            
                                connection.Close();
                                return View(model);
                            

                    }
                    return View();
                }
            }
        }


        public ActionResult Delete(int EmployeeID)
            // EmployeeID is the variable that allows us to change that Value
        {

            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;
    
            var employeeDetails = new EmployeeDirectory.Models.EmployeeModel();

            string DELETE = $"DELETE FROM StaffModel WHERE EmployeeID={EmployeeID}";
            // calling the DELETE method from StaffModel
            // EmployeeID QUOTATION = DATABASE
            // EmployeeID PARAMETER = VALUE

            Console.WriteLine("Connecting to SQL Server.");

            SqlConnection connection = new SqlConnection(newConnection);
            using (connection)
            {
                SqlCommand cmd = new SqlCommand(DELETE, connection);
                connection.Open();

                var model = new List<EmployeeDirectory.Models.EmployeeModel>();

                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {

                        employeeDetails.EmployeeID += (int)reader["EmployeeID"];
                        employeeDetails.EmployeeName += reader["EmployeeName"].ToString();
                        employeeDetails.JobTitle += reader["JobTitle"].ToString();
                        employeeDetails.WorkPlace += reader["WorkPlace"].ToString();
                        employeeDetails.Email += reader["Email"].ToString();
                        employeeDetails.PhoneNumber += reader["PhoneNumber"].ToString();

                        model.Remove(employeeDetails);
                    }
                    return RedirectToAction("Select");
                }
            }
        }


        [HttpPost]
        public ActionResult Insert(int EmployeeID, string EmployeeName, string JobTitle, string WorkPlace, string Email, string PhoneNumber)
        {

            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;

            string INSERT = $"INSERT INTO StaffModel VALUES ({EmployeeID}, '{EmployeeName}', '{JobTitle}', '{WorkPlace}', '{Email}', '{PhoneNumber}')";


            Console.WriteLine("Connecting to SQL Server.");

            SqlConnection connection = new SqlConnection(newConnection);
           
            using (connection)
            {
                SqlCommand cmd = new SqlCommand(INSERT, connection);
                connection.Open();

            

                cmd.Parameters.AddWithValue("EmployeeID", EmployeeID);
                cmd.Parameters.AddWithValue("EmployeeName", EmployeeName);
                cmd.Parameters.AddWithValue("JobTitle", JobTitle);
                cmd.Parameters.AddWithValue("WorkPlace", WorkPlace);
                cmd.Parameters.AddWithValue("Email", Email);
                cmd.Parameters.AddWithValue("PhoneNumber", PhoneNumber);

                cmd.ExecuteNonQuery();

                return RedirectToAction("Select");
            }
        }

        [HttpPost]
        public ActionResult Update(int EmployeeID, string EmployeeName, string JobTitle, string WorkPlace, string Email, string PhoneNumber)
        {
            {
            EmployeeDirectory.Methods.Connection connectionString = new EmployeeDirectory.Methods.Connection();
            string newConnection = connectionString.connectionString;

EmployeeDirectory/Views/Methods/Insert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using System;
@using System.Data.SqlClient;
@{
}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
<link href="https://blogfonts.com/css/aWQ9MTIyNjAwJnN1Yj02MDAmYz1hJnR0Zj1BUkxSREJELnR0ZiZuPWFyaWFsLXJvdW5kZWQtbXQtYm9sZA/Arial Rounded MT Bold.ttf" rel="stylesheet" type="text/css" />
@model List<EmployeeDirectory.Models.EmployeeModel>
<style>



    * {
        padding: 0;
        margin: 0;
    }

    h1 {
        margin-top: -1em;
        text-align: center;
        color: #394347;
        font-family: 'arial-rounded-mt-bold', sans-serif;
        padding: 1.25em;
    }

    input {
        font-size: 1em;
    }


    table tr td {
        padding: 0.5em;
        border: 1px solid #394347;
        background-color: #394347;
        color: #F7F410;
        font-weight: bolder;
        padding: 0.5em;
        font-size: 1.25em;
    }

    .save {
        background-color: #394347;
        border-radius: 25px;
        color: #fff;
        font-family: 'arial-rounded-mt-bold', sans-serif;
        font-size: 1.75em;
        text-align: center;
        justify-content: center;
        align-items: center;
        display: block;
        margin: 0 auto;
        opacity: 0.5;
        font-weight: bolder;
        text-decoration: none;
        border-style: hidden;
        margin-top: 1.25em;
        /*Transition*/
        -webkit-transition: all 1.5s ease;
        -moz-transition: all 1.5s ease;
        -o-transition: all 1.5s ease;
        height: 40px;
        width: 125px;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
    }

        .save:hover {
            background-color: #394347;
            color: #F7F410;
            opacity: 1;
            -webkit-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            -moz-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
        }


    .employee-container {
        font-family: 'Roboto', sans-serif;
    }

    table {
        margin-left: auto;
        margin-right: auto;
    }

    .return {
        align-content: center;
        margin-top: 2em;
        margin-left: 1em;
        background-color: #394347;
        border-radius: 25px;
        color: #fff;
        font-family: 'arial-rounded-mt-bold', sans-serif;
        font-size: 1.25em;
        text-align: center;
        justify-content: start;
        opacity: 0.5;
        font-weight: bolder;
        text-decoration: none;
        border-style: hidden;
        /*Transition*/
        -webkit-transition: all 1.5s ease;
        -moz-transition: all 1.5s ease;
        -o-transition: all 1.5s ease;
        height: 40px;
        width: 100px;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
    }

    .divider {
        padding: 2em;
    }

    .return:hover {
        background-color: #394347;
        color: #F7F410;
        opacity: 1;
        -webkit-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
        -moz-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
        box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
    }
</style>
<div class="employee-container">
    <form action="/Methods/Select" method="get">
        <button class="return">Return</button>
    </form>
    <h1>Add Employee</h1>
    <form action="/Methods/Insert" method="post">
        <table>
            <tr>
                <td>Employee ID: </td>
                <td><input type="text" name="EmployeeID" /></td>
            </tr>
            <tr>
                <td>Employee Name: </td>
                <td><input type="text" name="EmployeeName" /></td>
            </tr>
            <tr>
                <td>Job Title</td>
                <td><input type="text" name="JobTitle" /></td>
            </tr>
            <tr>
                <td>Work Place: </td>
                <td><input type="text" name="WorkPlace" /></td>
            </tr>
            <tr>
                <td>Email: </td>
                <td><input type="text" name="Email" /></td>
            </tr>
            <tr>
                <td>Phone Number: </td>
                <td><input type="text" name="PhoneNumber" /></td>
            </tr>
        </table>
        <input class="save" type="submit" value="Save" />
    </form>
</div>

<br>


EmployeeDirectory/Views/Methods/Login.cshtml
@{
}

<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
<link href="https://blogfonts.com/css/aWQ9MTIyNjAwJnN1Yj02MDAmYz1hJnR0Zj1BUkxSREJELnR0ZiZuPWFyaWFsLXJvdW5kZWQtbXQtYm9sZA/Arial Rounded MT Bold.ttf" rel="stylesheet" type="text/css" />


@* blue background-color: #1e4e9d
    grey: #394347
    yellow: #F7F410
*@

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>

    * {
        padding: 0;
        margin: 0;
    }


    .login-container {
        font-family: 'Roboto', sans-serif;
        display: block;
        background-color: #394347;
        border-radius: 25px;
        height: 45vh;
        width: 60vh;
        margin: auto;
        margin-top: 2.5em;
        margin-bottom: 2.5em;
        padding: 1em;
        justify-content: center;
        text-align: center;
    }


    h3 {
        font-size: 2em;
        margin-top: 0.25em;
        font-weight: bolder;
        color: #fff;
        font-family: 'arial-rounded-mt-bold', sans-serif;
        margin-bottom: 1em;
    }

    h4 {
        font-size: 1.25em;
        margin-top: 0.25em;
        font-weight: bolder;
        color: #fff;
    }

    .email, .password {
        margin: 1em;
    }

    .submitbutton {
        background-color: #fff;
        border-radius: 25px;
        color: #394347;
        font-family: 'arial-rounded-mt-bold', sans-serif;
        font-size: 1.25em;
        text-align: center;
        justify-content: center;
        align-items: center;
        display: block;
        margin: 0 auto;
        opacity: 0.5;
        font-weight: bolder;
        text-decoration: none;
        border-style: hidden;
        margin-top: 2em;
        /*Transition*/
        -webkit-transition: all 1.5s ease;
        -moz-transition: all 1.5s ease;
        -o-transition: all 1.5s ease;
        height: 40px;
        width: 100px;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
    }

        .submitbutton:hover {
            background-color: #394347;
            color: #F7F410;
            opacity: 1;
            -webkit-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            -moz-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            border-style: solid;
            border-color: #F7F410;
        }

    .email input, .password input {
        border-radius: 25px;
        padding-left: 1.5em;
        padding: 0.5em, 0em;
        height: 5vh;
        width: 40vh;
        margin-top: 1em;
        text-align: left;
        font-size: 1em;
        border-style: solid;
        border-color: #fff;
    }

</style>

<form class="login" action="/Methods/Login" method="get">

    <br />
    <div class="login-container">

        <h3 class="login-title" align="center">Sign In</h3>

        <div class="email">
            <h4>Email:</h4>
            <input type="text" name="Email" placeholder="Email" />
        </div>
        <div class="password">
            <h4>Password: </h4>
            <input type="password" name="Password" placeholder="Password" />
        </div>

        <input class="submitbutton" type="submit" value="Sign In" />


    </div>
</form>

EmployeeDirectory/Views/Methods/Search.cshtml
@using System;
@using System.Data.SqlClient;
@{
// this calls 'model' from MethodsController
    @model List<EmployeeDirectory.Models.EmployeeModel>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://blogfonts.com/css/aWQ9MTIyNjAwJnN1Yj02MDAmYz1hJnR0Zj1BUkxSREJELnR0ZiZuPWFyaWFsLXJvdW5kZWQtbXQtYm9sZA/Arial Rounded MT Bold.ttf" rel="stylesheet" type="text/css" />

    <style>



        * {
            padding: 0;
            margin: 0;
        }

        h1 {
            margin-top: 1em;
            text-align: center;
            color: #394347;
            font-family: 'arial-rounded-mt-bold', sans-serif;
        }

        table tr th {
            background-color: #394347;
            color: #F7F410;
            font-weight: bolder;
            padding: 0.5em;
            border: 1px solid #fff;
        }

        table tr td {
            padding: 0.5em;
            border: 1px solid #394347;
        }


        .employee-container {
            font-family: 'Roboto', sans-serif;
        }

        table {
            margin-left: auto;
            margin-right: auto;
            border-collapse: collapse;
            border: 1px solid #394347;
        }

        .search-container {
            display: flex;
            align-items: center;
            justify-content: center;
        }

            .search-container button {
                color: #fff;
                padding: 0.2em;
                border-style: hidden;
                border-radius: 25px;
                background-color: #394347;
                font-size: 1em;
                font-weight: bolder;
                width: 5em;
            }


            .search-container input {
                border-radius: 25px;
                padding: 0.2em;
                text-align: left;
                font-size: 1em;
                border-style: solid;
                border-color: #394347;
            }

            .search-container placeholder {
                color: #394347;
            }

        .delete a {
            text-decoration: none;
            color: #394347;
        }

            .delete a:hover {
                text-decoration: underline;
                color: black;
                font-weight: bolder;
            }

        .return {
            background-color: #394347;
            border-radius: 25px;
            color: #fff;
            font-family: 'arial-rounded-mt-bold', sans-serif;
            font-size: 1.5em;
            text-align: center;
            justify-content: center;
            align-items: center;
            display: block;
            margin: 0 auto;
            opacity: 0.5;
            font-weight: bolder;
            text-decoration: none;
            border-style: hidden;
            /*Transition*/
            -webkit-transition: all 1.5s ease;
            -moz-transition: all 1.5s ease;
            -o-transition: all 1.5s ease;
            height: 40px;
            width: 125px;
            -webkit-transition: all 0.5s ease;
            -moz-transition: all 0.5s ease;
            -o-transition: all 0.5s ease;
        }

        .return:hover {
            background-color: #394347;
            color: #F7F410;
            opacity: 1;
            -webkit-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            -moz-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
        }
    </style>

<div class="employee-container">
    <h1>Employee Details</h1>

    <br />

    <div class="search-container">
        <form action="/Methods/Search">
            <input type="text" placeholder="Search Employee..." name="EmployeeID">
            <button type="submit" asp-area="" asp-controller="Methods" asp-action="Search" asp-route-EmployeeID="">Submit</button>
        </form>
    </div>

    <br />

    <table>
        <tr>
            <th>Employee ID </th>
            <th>Employee Name </th>
            <th>Job Title </th>
            <th>Workplace </th>
            <th>Email </th>
            <th>Phone Number </th>
            <th>HR Action</th>
        </tr>
        @foreach (var employeeDetails in Model)
        {
        // this calls 'employeeDetails' from MethodsController
        <tr>
            <td>@employeeDetails.EmployeeID</td>
            <td>@employeeDetails.EmployeeName</td>
            <td>@employeeDetails.JobTitle</td>
            <td>@employeeDetails.WorkPlace</td>
            <td>@employeeDetails.Email</td>
            <td>@employeeDetails.PhoneNumber</td>
            <td class="delete">@Html.ActionLink("Delete", "Delete", new { EmployeeID = employeeDetails.EmployeeID })</td> @*Calling Delete variable and assigns it to Employee ID in the DataBase*@

        </tr>
        }
    </table>
</div>
        <br>
        <form action="/Methods/Select" method="get">
            <button class="return">Return</button>
        </form>
    }


EmployeeDirectory/Views/Methods/Select.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using System;
@using System.Data.SqlClient;
@{
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://blogfonts.com/css/aWQ9MTIyNjAwJnN1Yj02MDAmYz1hJnR0Zj1BUkxSREJELnR0ZiZuPWFyaWFsLXJvdW5kZWQtbXQtYm9sZA/Arial Rounded MT Bold.ttf" rel="stylesheet" type="text/css" />

    <style>


        * {
            padding: 0;
            margin: 0;
        }

        h1 {
            margin-top: 1em;
            text-align: center;
            color: #394347;
            font-family: 'arial-rounded-mt-bold', sans-serif;
        }


        table tr th {
            background-color: #394347;
            color: #F7F410;
            font-weight: bolder;
            padding: 0.5em;
            border: 1px solid #fff;
        }

        table tr td {
            padding: 0.5em;
            border: 1px solid #394347;
        }


        .employee-container {
            font-family: 'Roboto', sans-serif;
        }

        table {
            margin-left: auto;
            margin-right: auto;
            border-collapse: collapse;
            border: 1px solid #394347;
        }

        .search-container {
            display: flex;
            align-items: center;
            justify-content: center;
        }

            .search-container button {
                color: #fff;
                padding: 0.2em;
                border-style: hidden;
                border-radius: 25px;
                background-color: #394347;
                font-size: 1em;
                font-weight: bolder;
                width: 5em;
            }


            .search-container input {
                border-radius: 25px;
                padding: 0.2em;
                text-align: left;
                font-size: 1em;
                border-style: solid;
                border-color: #394347;
            }

            .search-container placeholder {
                color: #394347;
            }

        .delete a {
            text-decoration: none;
            color: #394347;
        }

            .delete a:hover {
                text-decoration: underline;
                color: black;
                font-weight: bolder;
            }

        .buttonsContainer{
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }

        .return {
            background-color: #394347;
            border-radius: 25px;
            color: #fff;
            font-family: 'arial-rounded-mt-bold', sans-serif;
            font-size: 1.25em;
            text-align: center;
            justify-content: center;
            align-items: center;
            display: block;
            margin: 0 auto;
            opacity: 0.5;
            font-weight: bolder;
            text-decoration: none;
            border-style: hidden;
            /*Transition*/
            -webkit-transition: all 1.5s ease;
            -moz-transition: all 1.5s ease;
            -o-transition: all 1.5s ease;
            height: 40px;
            width: 185px;
            -webkit-transition: all 0.5s ease;
            -moz-transition: all 0.5s ease;
            -o-transition: all 0.5s ease;
        }

        .divider{
            padding: 2em;
        }

            .return:hover {
                background-color: #394347;
                color: #F7F410;
                opacity: 1;
                -webkit-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
                -moz-box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
                box-shadow: 0px 0px 20px#393e41(255,255,255,0.8);
            }
    </style>
    // this calls 'model' from MethodsController
    @model List<EmployeeDirectory.Models.EmployeeModel>
<div class="employee-container">
    <h1>Employee Details</h1>

    <br />

    <div class="search-container">
        <form action="/Methods/Search">
            <input type="text" placeholder="Search Employee..." name="EmployeeID">
            <button type="submit" asp-area="" asp-controller="Methods" asp-action="Search" asp-route-EmployeeID="">Submit</button>
        </form>
    </div>

    <br />

    <table>
        <tr>
            <th>Employee ID </th>
            <th>Employee Name </th>
            <th>Job Title </th>
            <th>Workplace </th>
            <th>Email </th>
            <th>Phone Number </th>
            <th>HR Action</th>
        </tr>
        @foreach (var employeeDetails in Model)
        {
            // this calls 'employeeDetails' from MethodsController
            <tr>
                <td>@employeeDetails.EmployeeID</td>
                <td>@employeeDetails.EmployeeName</td>
                <td>@employeeDetails.JobTitle</td>
                <td>@employeeDetails.WorkPlace</td>
                <td>@employeeDetails.Email</td>
                <td>@employeeDetails.PhoneNumber</td>
                <td class="delete">@Html.ActionLink("Delete", "Delete", new { EmployeeID = employeeDetails.EmployeeID })</td> @*Calling Delete variable and assigns it to Employee ID in the DataBase*@

            </tr>
        }
    </table>


    <br />
    <div class="buttonsContainer">
        <div class="paddingInsert">
            <form action="/Methods/Insert" method="get">
                <button class="return">Add Employee</button>
            </form>
        </div>
        <div class="divider"></div>
        <div class="paddingUpdate">
            <form action="/Methods/Update" method="get">
                <button class="return">Update Employee</button>
            </form>
        </div>
    </div>

    </div>

    }

